{% set name = "memor" %}
{% set version = "0.8" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/memor
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.7
    run:
        - python >=3.7
about:
    home: https://github.com/openscilab/memor
    license: MIT
    license_family: MIT
    summary: Memor: Reproducible Structured Memory for LLMs
    description: |
	With Memor, users can store their LLM conversation history using an intuitive and structured data format.
    It abstracts user prompts and model responses into a "Session", a sequence of message exchanges.
    In addition to the content, it includes details like decoding temperature and token count of each message.
    Therefore users could create comprehensive and reproducible logs of their interactions.
    Because of the model-agnostic design, users can begin a conversation with one LLM and switch to another keeping the context the same.
    For example, they might use a retrieval-augmented model (like RAG) to gather relevant context for a math problem, and then switch to a model better suited for reasoning to solve the problem based on the retrieved information presented by Memor.
    Website: https://openscilab.com
    Repo: https://github.com/openscilab/memor
extra:
    recipe-maintainers:
        - sepandhaghighi
        - sadrasabouri
