{% set name = "memor" %}
{% set version = "0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/memor
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.6
    run:
        - python >=3.6
about:
    home: https://github.com/openscilab/memor
    license: MIT
    license_family: MIT
    summary: Memor: A Python Library for Managing and Transferring Conversational Memory Across LLMs
    description: |
	Memor is a library designed to help users manage the memory of their interactions with Large Language Models (LLMs). It enables users to seamlessly access and utilize the history of their conversations when prompting LLMs. That would create a more personalized and context-aware experience. Memor stands out by allowing users to transfer conversational history across different LLMs, eliminating cold starts where models don\'t have information about user and their preferences. Users can select specific parts of past interactions with one LLM and share them with another.By bridging the gap between isolated LLM instances, Memor revolutionizes the way users interact with AI by making transitions between models smoother.
	
        Website: https://openscilab.com

        Repo: https://github.com/openscilab/memor
extra:
    recipe-maintainers:
        - sepandhaghighi
        - AHReccese
        - sadrasabouri
